#!/usr/bin/env bash
# script to transfer files using scp
R_PATH=$1
IP=$2
R_USER=$3
R_SSH_KEY=$4
if [[ $# -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [[ $# -eq 4 ]]
then
	scp -o StrictHostKeyChecking=no -i "$R_SSH_KEY" "$R_PATH" "$R_USER"@"$IP":~/
elif [[ $# -eq 3 ]]
then
        scp -o StrictHostKeyChecking=no "$R_PATH" "$R_USER"@"$IP":~/
fi
