#!/usr/bin/env bash
# Script to create a redirection
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Ceci n'est pas une page" > /var/www/html/error404.html
redurl="	rewrite ^/error_page 404 /error404.html;"
sudo sed -i "54i $redurl" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
