#!/usr/bin/env bash
# Database backup script
if [[ $# -eq 1 ]]; then
file_date=$(date '+%d-%m-%Y')
mysqldump -h localhost -u root -p"$1"  --all-databases  > backup.sql &&
echo "backup.sql"
gzip -c backup.sql > "$file_date".tar.gz
fi
