#!/usr/bin/env bash
# Display "Best School" 10 times using until if 8 say "Hi"
i=0
while [ $i -le 9 ]
do
	if [ "$i" == 8 ]
	then
		echo "good luck"
	elif [ "$i" == 4 ]
	then
		echo "bad luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
