#!/usr/bin/env bash
# Display "numer" 10 but badluck for 4, 9 and 17
i=0
while [ $i -le 20 ]
do
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	*)
		echo $i
		;;
	esac
	i=$(( i + 1 ))
done
