#!/usr/bin/env bash
# File detection and info
file=school
if test -e "$file"; then
	echo "school file exists"
	if test -s "$file"; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if test -f "$file"; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
