#!/usr/bin/env bash
# local host and facebook definition modifier
cp /etc/hosts ~/hosts.new
sed -i "/localhost/d" ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
echo "127.0.0.2    localhost" >> ~/hosts.new
echo "8.8.8.8    facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
