#!/usr/bin/env bash
# local host and facebook definition modifier
cp /etc/hosts ~/hosts.new
sudo sed -i "s/.*[0-9]*localhost$/127.0.0.2       localhost/" ~/hosts.new
sudo ed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
echo "8.8.8.8    facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
